import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import type { TaxExportPackage } from './taxExportPackage';
import { formatCents } from './rounding';

export async function generateScheduleCSummaryPdf(input: {
  pkg: TaxExportPackage;
  appVersion: string;
}): Promise<Uint8Array> {
  const { pkg, appVersion } = input;

  const doc = await PDFDocument.create();
  const page = doc.addPage([612, 792]);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

  let y = 760;
  const left = 48;

  const drawLine = (text: string, opts?: { bold?: boolean }) => {
    const f = opts?.bold ? fontBold : font;
    page.drawText(text, {
      x: left,
      y,
      size: 11,
      font: f,
      color: rgb(0, 0, 0),
    });
    y -= 16;
  };

  drawLine(`Bozzy Schedule C Summary (organized for tax prep)`, { bold: true });
  drawLine(`Tax year: ${pkg.metadata.taxYear}`);
  drawLine(`Date range: ${pkg.metadata.dateStart} to ${pkg.metadata.dateEnd}`);
  drawLine(`Basis: cash`);
  drawLine(`Currency: USD`);
  drawLine(`Generated by Bozzy ${appVersion} at ${pkg.metadata.createdAt}`);

  y -= 8;
  drawLine('Schedule C totals (verify with your tax professional):', { bold: true });
  drawLine('NOTE: Expense amounts shown as positive for manual entry.', { bold: false });
  y -= 4;

  // Use scheduleCLineItems with amount_for_entry (positive for expenses)
  for (const item of pkg.scheduleCLineItems) {
    const isExpense = item.rawSignedAmount < 0;
    const displayAmount = item.amountForEntry;
    const label = isExpense 
      ? `${item.scheduleCLineName} (N${item.scheduleCRefNumber}) - enter as expense`
      : `${item.scheduleCLineName} (N${item.scheduleCRefNumber})`;
    
    drawLine(`${label}: $${formatCents(displayAmount)}`);
  }

  y -= 8;
  drawLine(`Net profit: $${formatCents(pkg.scheduleC.netProfit)}`, { bold: true });

  if (pkg.scheduleC.warnings.length > 0) {
    y -= 8;
    drawLine('Notes:', { bold: true });
    for (const w of pkg.scheduleC.warnings) {
      drawLine(`- ${w}`);
    }
  }

  return await doc.save();
}
