import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import type { TaxExportPackage } from './taxExportPackage';
import { formatCents } from './rounding';

export async function generateScheduleCSummaryPdf(input: {
  pkg: TaxExportPackage;
  appVersion: string;
}): Promise<Uint8Array> {
  const { pkg, appVersion } = input;

  const doc = await PDFDocument.create();
  const page = doc.addPage([612, 792]);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

  let y = 760;
  const left = 48;

  const drawLine = (text: string, opts?: { bold?: boolean }) => {
    const f = opts?.bold ? fontBold : font;
    page.drawText(text, {
      x: left,
      y,
      size: 11,
      font: f,
      color: rgb(0, 0, 0),
    });
    y -= 16;
  };

  drawLine(`GigLedger Schedule C Summary (organized for tax prep)`, { bold: true });
  drawLine(`Tax year: ${pkg.metadata.taxYear}`);
  drawLine(`Date range: ${pkg.metadata.dateStart} to ${pkg.metadata.dateEnd}`);
  drawLine(`Basis: cash`);
  drawLine(`Currency: USD`);
  drawLine(`Generated by GigLedger ${appVersion} at ${pkg.metadata.createdAt}`);

  y -= 8;
  drawLine('Schedule C totals (verify with your tax professional):', { bold: true });

  drawLine(`Gross receipts (N293): $${formatCents(pkg.scheduleC.grossReceipts)}`);
  drawLine(`Returns and allowances (N296): $${formatCents(-Math.abs(pkg.scheduleC.returnsAllowances))}`);
  drawLine(`Cost of goods sold (N295): $${formatCents(-Math.abs(pkg.scheduleC.cogs))}`);

  const refs = Object.entries(pkg.scheduleC.expenseTotalsByScheduleCRefNumber)
    .map(([k, v]) => ({ ref: Number(k), amount: v || 0 }))
    .filter(({ ref }) => ref !== 293 && ref !== 296 && ref !== 295 && ref !== 303 && ref !== 302)
    .sort((a, b) => a.ref - b.ref);

  for (const r of refs) {
    drawLine(`Expense (N${r.ref}): $${formatCents(-Math.abs(r.amount))}`);
  }

  if (pkg.scheduleC.otherExpensesBreakdown.length > 0) {
    drawLine('Other expenses (N302):', { bold: true });
    for (const item of pkg.scheduleC.otherExpensesBreakdown) {
      drawLine(`${item.name}: $${formatCents(-Math.abs(item.amount))}`);
    }
  }

  if (pkg.scheduleC.otherIncome !== 0) {
    drawLine(`Other income (N303): $${formatCents(Math.abs(pkg.scheduleC.otherIncome))}`);
  }

  y -= 8;
  drawLine(`Net profit: $${formatCents(pkg.scheduleC.netProfit)}`, { bold: true });

  if (pkg.scheduleC.warnings.length > 0) {
    y -= 8;
    drawLine('Notes:', { bold: true });
    for (const w of pkg.scheduleC.warnings) {
      drawLine(`- ${w}`);
    }
  }

  return await doc.save();
}
