// Generated by supabase gen types typescript
// This is a placeholder - run `npm run supabase:types` after setting up Supabase

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      payers: {
        Row: {
          id: string
          user_id: string
          name: string
          type: 'Venue' | 'Client' | 'Platform' | 'Other' | 'Individual' | 'Corporation'
          contact_email: string | null
          notes: string | null
          expect_1099: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          type: 'Venue' | 'Client' | 'Platform' | 'Other' | 'Individual' | 'Corporation'
          contact_email?: string | null
          notes?: string | null
          expect_1099?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          type?: 'Venue' | 'Client' | 'Platform' | 'Other' | 'Individual' | 'Corporation'
          contact_email?: string | null
          notes?: string | null
          expect_1099?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      gigs: {
        Row: {
          id: string
          user_id: string
          payer_id: string
          date: string
          title: string
          location: string | null
          city: string | null
          state: string | null
          country: string | null
          gross_amount: number
          tips: number
          fees: number
          per_diem: number
          other_income: number
          net_amount: number
          payment_method: string | null
          invoice_link: string | null
          paid: boolean
          taxes_withheld: boolean
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          payer_id: string
          date: string
          title: string
          location?: string | null
          city?: string | null
          state?: string | null
          country?: string | null
          gross_amount: number
          tips?: number
          fees?: number
          per_diem?: number
          other_income?: number
          net_amount: number
          payment_method?: string | null
          invoice_link?: string | null
          paid?: boolean
          taxes_withheld?: boolean
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          payer_id?: string
          date?: string
          title?: string
          location?: string | null
          city?: string | null
          state?: string | null
          country?: string | null
          gross_amount?: number
          tips?: number
          fees?: number
          per_diem?: number
          other_income?: number
          net_amount?: number
          payment_method?: string | null
          invoice_link?: string | null
          paid?: boolean
          taxes_withheld?: boolean
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      expenses: {
        Row: {
          id: string
          user_id: string
          gig_id: string | null
          date: string
          vendor: string | null
          description: string
          category: 'Travel' | 'Meals' | 'Lodging' | 'Supplies' | 'Marketing' | 'Education' | 'Software' | 'Fees' | 'Equipment' | 'Other'
          amount: number
          receipt_url: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          gig_id?: string | null
          date: string
          vendor?: string | null
          description: string
          category: 'Travel' | 'Meals' | 'Lodging' | 'Supplies' | 'Marketing' | 'Education' | 'Software' | 'Fees' | 'Equipment' | 'Other'
          amount: number
          receipt_url?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          gig_id?: string | null
          date?: string
          vendor?: string | null
          description?: string
          category?: 'Travel' | 'Meals' | 'Lodging' | 'Supplies' | 'Marketing' | 'Education' | 'Software' | 'Fees' | 'Equipment' | 'Other'
          amount?: number
          receipt_url?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      mileage: {
        Row: {
          id: string
          user_id: string
          gig_id: string | null
          date: string
          purpose: string
          start_location: string
          end_location: string
          miles: number
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          gig_id?: string | null
          date: string
          purpose: string
          start_location: string
          end_location: string
          miles: number
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          gig_id?: string | null
          date?: string
          purpose?: string
          start_location?: string
          end_location?: string
          miles?: number
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      payer_type: 'Venue' | 'Client' | 'Platform' | 'Other' | 'Individual' | 'Corporation'
      expense_category: 'Travel' | 'Meals' | 'Lodging' | 'Supplies' | 'Marketing' | 'Education' | 'Software' | 'Fees' | 'Equipment' | 'Other'
    }
  }
}
